# Generated by Django 4.0.6 on 2022-07-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='bscToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('scannerLink', models.URLField(max_length=128, verbose_name='name')),
                ('exchangerLink', models.URLField(max_length=128, verbose_name='exchanger')),
                ('name', models.CharField(max_length=50, verbose_name='Token name')),
                ('symbol', models.CharField(max_length=20, verbose_name='Token symbol')),
                ('address', models.CharField(max_length=45, verbose_name='Token address')),
                ('networkName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listOfTokens.network')),
            ],
            options={
                'ordering': ['scannerLink', 'exchangerLink', 'created_on'],
                'abstract': False,
            },
        ),
    ]
