# Generated by Django 4.0.6 on 2022-07-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listOfTokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='bsctoken',
            name='networkName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listOfTokens.network'),
        ),
    ]
