# Generated by Django 4.0.6 on 2022-08-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listOfTokens', '0002_user_alter_bsctoken_networkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsctoken',
            name='networkName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='listOfTokens.network'),
        ),
    ]
